In [2]:
import numpy

In [3]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


In [5]:
array1 = numpy.full(6, 7)
print(array1)

[7 7 7 7 7 7]


In [6]:
array1 = numpy.full(6, 0)
array2 = numpy.zeros(6, dtype=int)
    
print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [7]:
array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype=int)
    
print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


In [11]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)
    
print(array1)
print()
print(array2)

[0.24355172 0.65394577 0.18397283 0.8659945  0.62450635 0.83479431]

[0.84776183 0.23562982 0.01016008 0.11029282 0.20095261 0.36513058]


In [12]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [13]:
array1 = numpy.arange(2, 7)
print(array1)

[2 3 4 5 6]


In [14]:
array1 = numpy.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]
