In [1]:
import numpy as np

In [3]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

각 원소를 비교해 4보다 크면 True 작으면 False  
각 원소를 비교해 짝수면 True 홀수면 False

In [6]:
booleans = np.array([True, True, False, True, True, False, True, True, False, True])

In [7]:
np.where(booleans)

(array([0, 1, 3, 4, 6, 7, 9], dtype=int64),)

True가 담긴 자리만 출력

In [8]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [9]:
np.where(array1 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [10]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [11]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

**흥부부대찌개 목표 일 매출 문제**

In [13]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

In [14]:
yen_array = np.array(revenue_in_yen)

In [15]:
filter = np.where(yen_array < 200000)
bad_days_revenue = yen_array[filter]

In [16]:
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])